### ISSUE TITLE
Issue building in XCode

### ISSUE THREAD

**Issue by AirGeoff** [foursquare/pilgrim-unity-package#17]
Hi Pilgrim team,

I have run into an issue building for xcode and it looks like it could be related to the Pilgrim SDK. In xcode the build is failing and I am getting an error that Command PhaseScriptExecution failed with a nonzero exit code. Here is the full error code from xcode:

/Users/geoffgoeres-hill/Library/Developer/Xcode/DerivedData/Unity-iPhone-adhkmrncivefnlanoajzziszytus/Build/Products/ReleaseForRunning-iphoneos/AirEverywhereMVP.app/Frameworks/Pilgrim.framework/strip-frameworks.sh: line 18:
: command not found
/Users/geoffgoeres-hill/Library/Developer/Xcode/DerivedData/Unity-iPhone-adhkmrncivefnlanoajzziszytus/Build/Products/ReleaseForRunning-iphoneos/AirEverywhereMVP.app/Frameworks/Pilgrim.framework/strip-frameworks.sh: line 28:
: command not found
/Users/geoffgoeres-hill/Library/Developer/Xcode/DerivedData/Unity-iPhone-adhkmrncivefnlanoajzziszytus/Build/Products/ReleaseForRunning-iphoneos/AirEverywhereMVP.app/Frameworks/Pilgrim.framework/strip-frameworks.sh: line 29:
: command not found
/Users/geoffgoeres-hill/Library/Developer/Xcode/DerivedData/Unity-iPhone-adhkmrncivefnlanoajzziszytus/Build/Products/ReleaseForRunning-iphoneos/AirEverywhereMVP.app/Frameworks/Pilgrim.framework/strip-frameworks.sh: line 31: syntax error near unexpected token `{
'
/Users/geoffgoeres-hill/Library/Developer/Xcode/DerivedData/Unity-iPhone-adhkmrncivefnlanoajzziszytus/Build/Products/ReleaseForRunning-iphoneos/AirEverywhereMVP.app/Frameworks/Pilgrim.framework/strip-frameworks.sh: line 31: `code_sign() {
'
Command PhaseScriptExecution failed with a nonzero exit code

Can you please help me figure out how to resolve this so I can build to a device?

<img width="858" alt="Screen Shot 2019-06-05 at 1 36 26 PM" src="https://user-images.githubusercontent.com/47788677/58997220-6f21f100-87b0-11e9-9e6f-d72d068f352d.png">

**Comment by marchinram** [comment]
Hello, sorry for the delay on this, can you let me know what version you are using and what Xcode version you are using and I'll try to repro

**Comment by LLH-666** [comment]
Hello, I have encountered the same problem as you, how did you solve it?

@marchinram @AirGeoff @jonshea @agate @dustinkeitel 

My Xcode version:13.2.1
